name: Deploy Beta

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # So sentry can get the previous commit

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: dim.rsa
          known_hosts: ${{ secrets.REMOTE_HOST }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Bump release version (beta)
        id: bump_version
        run: echo '::set-output name=next-version::${{ steps.package-version.outputs.current-version }}.${{ github.run_number }}'

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build
        run: yarn build:beta
        env:
          VERSION: ${{ steps.bump_version.outputs.next-version }}
          WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
          WEB_OAUTH_CLIENT_ID: ${{ secrets.WEB_OAUTH_CLIENT_ID }}
          WEB_OAUTH_CLIENT_SECRET: ${{ secrets.WEB_OAUTH_CLIENT_SECRET }}
          DIM_API_KEY: ${{ secrets.DIM_API_KEY }}

      - name: Check Syntax
        run: yarn syntax

      - name: Deploy
        run: ./build/rsync-deploy.sh
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: beta.destinyitemmanager.com

      - name: Purge CloudFlare cache
        run: ./build/purge-cloudflare.sh
        env:
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          APP_DOMAIN: beta.destinyitemmanager.com

      - name: Publish Sentry release
        run: ./build/sentry-release.sh
        env:
          VERSION: ${{ steps.bump_version.outputs.next-version }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
