# Discord bot test without annoying others

name: discord bot test (manual only)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/949687534819102781/Cs0d_zHhnaBaGZXsJ8Bs3WF3TtJbKfjMOhvZ9CvtXpsJoQBUhceajRLO0wSsnGV0MbnQ
          DISCORD_EMBEDS: '[{"title":"PR Review Submitted - Approved", "color": 65280, "url":${{ toJSON(github.event.review.html_url) }},"description": "${{github.event.pull_request.user.login}}, ${{ github.event.review.user.login}} submitted a review for your PR: [${{github.event.pull_request.title}}]"  }]'
        uses: Ilshidur/action-discord@master
        with:
          args: "<@&622449489008918548> - ${{ steps.i18n-diff.outputs.insertions }} translations have been added/changed on crowdin. https://crowdin.com/project/destiny-item-manager"