# Run this workflow whenever en.json has keys updated and you have updated the keys in the other i18n files as well
# Does not notify #i18n in discord
name: i18n upload all (manual only)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DIM
        uses: actions/checkout@v2

      - name: sort locale ${lang}.json
        run: |
          allLocales=("en" "de" "es" "esMX" "fr" "it" "ja" "ko" "pl" "ptBR" "ru" "zhCHS" "zhCHT")
          for lang in ${allLocales[@]}; do
            jq -S . src/locale/$lang.json > src/locale/sorted_$lang.json && mv src/locale/sorted_$lang.json src/locale/$lang.json
          done

      - name: Upload updated ${lang}.json to crowdin
        uses: crowdin/github-action@1.4.7
        with:
          upload_sources: true
          upload_translations: true
          source: src/en.json
          translation: src/locale/%android_code%.json
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
