name: i18n-update

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'config/i18n.json'
      - 'src/locale/dim.json'

jobs:
  i18n-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: yarn i18n
        run: yarn i18n

      - name: Check for new files
        id: data
        run: echo ::set-output name=porcelain::"$(git status --porcelain)"

      - name: Please run `yarn i18n`
        if: steps.data.outputs.porcelain
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Please run `yarn i18n`

      - name: Fail the Build
        if: steps.data.outputs.porcelain
        uses: cutenode/action-always-fail@v1.0.0
