name: i18n-update

on:
  pull_request:
    paths:
      - 'config/i18n.json'
  push:
    branches:
      - "master"
    paths:
      - 'config/i18n.json'

jobs:
  i18n-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.I18N_PAT }}

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: yarn

    - name: Install
      run: yarn install --frozen-lockfile --prefer-offline

    - name: yarn i18n
      run: yarn i18n

    - name: Check for new files
      id: data
      run: echo ::set-output name=porcelain::"$(git status --porcelain)"

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: steps.data.outputs.porcelain
      with:
        commit_message: Apply i18n updates
