name: Jest & ESLint Annotate

on:
  workflow_run:
    workflows: ["PR Build"]
    types:
      - completed

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Download jest results
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "PR Build"
          workflow_conclusion: completed
          name: jest-results

      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          coverage-comment: false
          test-command: "echo done"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download ESLint results
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "PR Build"
          workflow_conclusion: completed
          name: eslint-results

      - name: Annotate ESLint Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint.results.json"
          fail-on-warning: true
