name: Jest & ESLint Annotate

on:
  workflow_run:
    workflows: ["PR Test & Lint"]
    types:
      - completed

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download jest-results artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "jest-results"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/jest-results.zip', Buffer.from(download.data));
      - run: unzip jest-results.zip
      
      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          coverage-comment: false
          test-command: "echo done"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download eslint-results artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "eslint-results"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/eslint-results.zip', Buffer.from(download.data));
      - run: unzip eslint-results.zip
      
      - name: Annotate ESLint Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint.results.json"
          fail-on-warning: true
