name: Jest & ESLint Annotate

on:
  workflow_run:
    workflows: ["PR Test & Lint"]
    types:
      - completed

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait 30 seconds
        run: |
          sleep 30

  jest:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - name: Download jest results
        uses: dawidd6/action-download-artifact@v2.17.0
        with:
          workflow: "PR Test & Lint"
          name: jest-results

      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          coverage-comment: false
          test-command: "echo done"

  lint:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - name: Download ESLint results
        uses: dawidd6/action-download-artifact@v2.17.0
        with:
          workflow: "PR Test & Lint"
          name: eslint-results

      - name: Annotate ESLint Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint.results.json"
          fail-on-warning: true
