name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3 # So sentry can get the previous commit

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      - name: set beta
        run: |
          echo "build_level='beta'" >> $GITHUB_ENV

      - name: Bump release version (beta)
        run: |
          echo "VERSION=${{ steps.package-version.outputs.current-version }}.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build beta
        run: yarn build:beta
        env:
          PR_BUILD: true

      # Upload webpack-stats.json to use on relative-ci.yaml workflow
      - name: Upload webpack stats artifact
        uses: relative-ci/agent-upload-artifact-action@v1
        with:
          webpackStatsFile: ./webpack-stats.json

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Jest Test
        run: yarn jest --json --outputFile="jest.results.json"

      - uses: actions/upload-artifact@v3
        with:
          name: jest-results
          path: jest.results.json

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Slug Action
        uses: rlespinasse/github-slug-action@4.0.0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Cache ESLint
        uses: actions/cache@v2
        env:
          cache-name: cache-eslint
        with:
          path: ~/.eslintcache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.eslintrc') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.eslintrc') }}
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Save ESLint Report JSON
        run: yarn lint-report:cached
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: eslint-results
          path: eslint.results.json
