name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3 # So sentry can get the previous commit

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Cache eslint
        uses: actions/cache@v2
        env:
          cache-name: cache-eslint
        with:
          path: ~/.eslintcache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.eslintrc') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.eslintrc') }}
            ${{ runner.os }}-${{ env.cache-name }}-

      # TODO: Gnu parallel for test/check
      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Test
        run: yarn test

      - name: Lint check
        run: |
          find . -type d -name "node_modules" -prune -o -type f -iregex '.*.ts\|.*.js\|.*.tsx\|.*.jsx' -exec ./build/set-mtime-to-md5.sh {} \;
          yarn lintcached:eslint

      # We set the default packtracker ENV vars
      - name: Build beta
        run: yarn build:beta
        env:
          PR_BUILD: true
